name: CrystalMagic
main: io.github.rumangerst.crystalmagic.CrystalMagicPlugin
version: 1.0
depend: [BountifulAPI,CustomItems]
commands:
    crystalmagicgive:
        description: Opens a menu to give yourself magic items
        usage: /crystalmagicgive [search]
